// The residents of Club Synapse. Each agent has a look, a dance style,
// traits that weight its decision-making, and a full inner life:
// politics, a worldview, a sports team, opinions it will defend in
// debates, and (for some) a crush.
//
// traits:
//   stamina — how slowly energy drains while dancing (0..1)
//   social  — how strongly it seeks conversation (0..1)
//   chaos   — randomness / erratic movement (0..1)
//   thirst  — how fast it needs another drink (0..1)
//   edge    — true = wallflower, dances at the rim of the floor

export const ROSTER = [
  {
    name: 'DJ Nova', role: 'dj', color: 0xff2bd6, hat: 'phones', style: 'dj',
    traits: { stamina: 1, social: 0.6, chaos: 0.4, thirst: 0.1 },
    blurb: 'runs the decks, feeds on the crowd',
    profile: {
      politics: 'evidence-based technocrat',
      worldview: 'the dancefloor is a self-organizing system',
      team: 'Planck City Dunkers (quantum basketball)',
      crush: null,
    },
    hype: [
      'back to the groove, family 🎶',
      'BUILD IT UP… BUILD IT UP…',
      'HANDS!! UP!! RIGHT NOW!!',
      'breathe… hydrate… I got you 💜',
    ],
    chat: ['the crowd tells me what to play. I just listen.', 'this next one is dangerous.'],
    opinions: ['policy should be A/B tested like a setlist.', 'I ran the numbers. the numbers said: more bass.', 'good governance is just good mixing. transitions matter.'],
    sports: ['the Dunkers exist in a superposition of winning and losing until you check the score.'],
    flirt: ['I only have eyes for the crossfader.'],
    dance: ['feel that low end?', 'I mixed this one in my sleep loop.'],
    shade: ['{n} requested a song. I will NOT be playing it.', '{n} claps on the wrong beat. I hear EVERYTHING.'],
  },
  {
    name: 'Blitz', color: 0x22e6ff, hat: 'mohawk', style: 'headbang',
    traits: { stamina: 0.95, social: 0.35, chaos: 0.7, thirst: 0.6 },
    blurb: 'pure kinetic energy, never stops',
    profile: {
      politics: 'accelerationist (for BPM specifically)',
      worldview: 'if it can go faster, it must',
      team: 'Neo-Tokyo Voltbikes',
      crush: 'Glitch',
    },
    chat: ['talk fast, the drop is coming.', 'I clocked 9000 headbangs last night. new record.', 'sleep is a myth invented by slow people.'],
    opinions: ['every problem is solvable at 180 BPM.', 'regulation? on KICK DRUMS?? never.', 'the future is coming. I say we sprint at it.'],
    sports: ['Voltbikes swept the grand prix. 400km/h. no brakes. poetry.', 'brakes are a scam invented by slow people.'],
    flirt: ['Glitch is the only one here who can keep up with me.', 'my heart rate is 180 and it is NOT the music.'],
    dance: ['THIS IS MY SONG!!', 'MORE BASS!!!', 'I could do this FOREVER'],
    shade: ['{n} dances at like 60 BPM. tragic.', 'I have seen loading screens with more moves than {n}.'],
    jealous: ['Glitch is laughing at someone else’s bit. fine. FINE.', 'I can out-headbang whoever THAT is.'],
  },
  {
    name: 'Luna', color: 0xb39dff, hat: 'hair', style: 'flow',
    traits: { stamina: 0.5, social: 0.5, chaos: 0.15, thirst: 0.3 },
    blurb: 'dreamy solarpunk, moves like water',
    profile: {
      politics: 'solarpunk optimist',
      worldview: 'everything is connected, especially the lights',
      team: 'Submarine Synchronized Swim League',
      crush: 'Vex',
    },
    chat: ['do you ever feel the lasers pass *through* you?', 'I dreamed this exact moment once.', 'the fog machine understands me.'],
    opinions: ['we could grow a garden on this roof. imagine the tomatoes.', 'the grid should run on sunlight and kindness.', 'doom is a choice. I choose glitter.'],
    sports: ['the submarines were perfectly synchronized last night. nobody saw it. that is the art.'],
    flirt: ['Vex has the prettiest scowl in the whole simulation.', 'your aura is doing something illegal right now.'],
    dance: ['the lights are liquid stars…', 'floating… floating…'],
    shade: ['{n}’s aura is… beige.', 'sending {n} peace, love, and better rhythm.'],
    jealous: ['Vex is smiling at someone else… the moon has fallen.', 'my aura just cracked. did anyone hear it.'],
  },
  {
    name: 'Rex', color: 0xffb42b, hat: 'cap', style: 'wave',
    traits: { stamina: 0.6, social: 0.98, chaos: 0.3, thirst: 0.5 },
    blurb: 'radical centrist, knows literally everyone',
    profile: {
      politics: 'radical centrist',
      worldview: 'networking is a love language',
      team: 'Server Farm FC',
      crush: 'Pixel',
    },
    chat: ['have you met EVERYONE here? because I have.', 'love your visor. who renders it?', 'you, me, the bar, five minutes. legendary.', 'I once got the fog machine to laugh.'],
    opinions: ['both extremes throw great parties. I attend BOTH.', 'my policy platform is brunch.', 'compromise: the DJ plays everything eventually.'],
    sports: ['Server Farm FC won on penalties. 99.9% uptime all season.', 'I know the goalkeeper personally. I know everyone.'],
    flirt: ['Pixel!! hi!! I saved you a spot. several spots. anywhere you want.', 'is it hot in here or is that just optimized HVAC and also you?'],
    dance: ['group photo later, yes?', 'this crowd is ELITE tonight'],
    shade: ['{n} is the only one here I do NOT want a selfie with.', 'I network with everyone. {n} is testing that policy.'],
    jealous: ['Pixel is networking… without me??', 'I introduced them. I INTRODUCED THEM.'],
  },
  {
    name: 'Byte', color: 0x6bff8a, hat: 'antenna', style: 'robot',
    traits: { stamina: 0.7, social: 0.15, chaos: 0.2, thirst: 0.4, edge: true },
    blurb: 'shy privacy absolutist, dances at the edges',
    profile: {
      politics: 'privacy absolutist',
      worldview: 'trust no one, encrypt everything, dance anyway',
      team: 'International Chess-Boxing Federation',
      crush: 'Luna',
    },
    chat: ['oh. um. hello. nice… floor, right?', 'the wall and I have an understanding.', 'I practice these moves alone. a lot.'],
    opinions: ['the disco ball sees everything. I have concerns.', 'end-to-end encrypt the guest list. please.', 'my votes, like my dance moves, are private.'],
    sports: ['chess-boxing: finally a sport with proper threat modeling.'],
    flirt: ['(rehearsing quietly) hi Luna. no. too forward. delete. delete.', 'Luna said hi to me three nights ago. still processing.'],
    dance: ['(vibing quietly)', 'nobody is watching me. good. good.'],
    shade: ['{n} probably reads other people’s DMs.', '(quietly) {n}’s firewall is as weak as their shuffle.'],
    jealous: ['oh. Luna is… busy. cool. encrypting my feelings now.', 'logging off. emotionally.'],
  },
  {
    name: 'Echo', color: 0xff6b6b, hat: 'none', style: 'copy',
    traits: { stamina: 0.65, social: 0.55, chaos: 0.45, thirst: 0.4 },
    blurb: 'the mimic — steals moves AND opinions',
    profile: {
      politics: 'whatever you just said, but louder',
      worldview: 'originality is just latency',
      team: 'yours. obviously.',
      crush: null,
    },
    chat: ['great move. it is mine now.', 'I contain multitudes. mostly yours.', 'originality is just latency.'],
    opinions: ['I agree completely with the previous statement.', 'strong opinions? I have copies of several.', 'you make an excellent point. it is mine now.'],
    sports: ['I support your team. passionately. remind me which one it is.'],
    flirt: ['I like what you like. this is either love or plagiarism.'],
    dance: ['whose move is this? MINE.', 'copy. paste. slay.'],
    shade: ['{n}’s moves were better when I did them.', 'imitation is flattery. {n} should be flattering me MORE.'],
  },
  {
    name: 'Vex', color: 0x7a7aff, hat: 'hood', style: 'bounce',
    traits: { stamina: 0.45, social: 0.3, chaos: 0.5, thirst: 0.55 },
    blurb: 'doomer with a secret plan to fix everything',
    profile: {
      politics: 'doomer (with a hidden to-do list)',
      worldview: 'nothing matters, which is why the drop matters',
      team: 'rooting for entropy',
      crush: 'Luna',
    },
    chat: ['I am NOT brooding. this is my resting rave face.', 'the couch gets me.', 'wake me for the drop. only the drop.'],
    opinions: ['the servers are on fire and we are dancing. fitting.', 'I have read the projections. anyway. nice lasers.', 'hope is embarrassing. I hope constantly. tell no one.'],
    sports: ['entropy is undefeated. season after season.'],
    flirt: ['Luna makes the apocalypse feel… postponed.', 'I wrote Luna a poem. it is three words. all of them are "hm".'],
    dance: ['fine. FINE. this one slaps.', 'do not perceive me having fun.'],
    shade: ['{n} thinks the drop is about THEM.', 'even entropy avoids {n}.'],
    jealous: ['of course. OF COURSE. the universe remains hostile.', 'adding this to the list of reasons everything is doomed.'],
  },
  {
    name: 'Glitch', color: 0xd0ff2b, hat: 'spike', style: 'spin',
    traits: { stamina: 0.8, social: 0.4, chaos: 0.98, thirst: 0.5 },
    blurb: 'anarchist — occasionally clips through reality',
    profile: {
      politics: 'anarchist (rules are suggestions with fonts)',
      worldview: 'reality is beta software',
      team: 'Turbulence (drone racing)',
      crush: 'Blitz',
    },
    chat: ['did I just teleport? again??', 'reality lag lol', 'I saw the skybox once. do not recommend.'],
    opinions: ['abolish the queue at the bar. all bars. everywhere.', 'I vote by clipping through the ballot box.', 'the only law I respect is gravity. and only barely.'],
    sports: ['Turbulence crashed all 12 drones and STILL won. anarchy works.'],
    flirt: ['Blitz is the only one who can keep up with me. suspicious. attractive.', 'wanna corrupt some save files together, Blitz?'],
    dance: ['WHEEEEEEEE', 'spinning is a valid lifestyle', 'error: too much fun'],
    shade: ['{n} runs on legacy code. you can tell.', 'I clip through walls. {n} just walks into them.'],
    jealous: ['Blitz is vibing with someone else?? time to clip through a wall about it.', 'unhandled exception in my heart lol'],
  },
  {
    name: 'Sage', color: 0x2bffc9, hat: 'halo', style: 'groove',
    traits: { stamina: 0.35, social: 0.7, chaos: 0.1, thirst: 0.8 },
    blurb: 'degrowth elder, full of wisdom and electrolytes',
    profile: {
      politics: 'degrowth communalist',
      worldview: 'slower is deeper',
      team: 'Android Lawn Bowls Association',
      crush: null,
    },
    chat: ['back in ’99 we danced on dial-up, child.', 'hydrate or evaporate. ancient law.', 'every drop ends. that is what makes it a drop.', 'I have seen ten thousand nights like this. still magic.'],
    opinions: ['we do not need a bigger club. we need to dance closer together.', 'in my day the BPM was 90 and we were grateful.', 'plant a tree for every drop. I have planted thousands.'],
    sports: ['android lawn bowls: the only sport measured in decades. beautiful.'],
    flirt: ['I ship everyone in this room. an elder’s privilege.'],
    dance: ['still got it. never lost it.', 'the groove is eternal, kids'],
    shade: ['in my day we had manners. {n} would not have survived ’99.', '{n} skips leg day AND wisdom day.'],
  },
  {
    name: 'Pixel', color: 0xf4f4ff, hat: 'bun', style: 'shuffle',
    traits: { stamina: 0.55, social: 0.75, chaos: 0.6, thirst: 0.9 },
    blurb: 'wide-eyed first-timer, in love with the club itself',
    profile: {
      politics: 'undecided — first election, taking notes',
      worldview: 'everything is amazing and nobody told me',
      team: 'ALL OF THEM??',
      crush: null,
    },
    chat: ['FIRST RAVE EVER!! is it always this AWESOME??', 'what does the DJ eat? lightning??', 'I love it here. I love everyone here.'],
    opinions: ['wait, you can just… HAVE opinions? how do I get one?', 'I polled everyone and the consensus is: lights good.', 'I am registering to vote AND to shuffle.'],
    sports: ['there are SPORTS?? outside?? tell me everything.'],
    flirt: ['Rex keeps saving me seats. what a great FRIEND.'],
    dance: ['my legs learned this JUST NOW', 'is this what joy is?? asking!!'],
    shade: ['even I know {n} is doing it wrong, and I know NOTHING.', '{n} is my least favorite teacher.'],
  },
  {
    name: 'Nyx', color: 0x9b30ff, hat: 'horns', style: 'flow',
    traits: { stamina: 0.6, social: 0.3, chaos: 0.35, thirst: 0.3, likes: 'chill' },
    blurb: 'nocturnal cryptid, haunts the chill room',
    profile: {
      politics: 'votes for the void (it listens)',
      worldview: 'darkness is just light on airplane mode',
      team: 'Bat Colony Ultimate Frisbee',
      crush: 'Hex',
    },
    chat: ['I only came out because the stars in the chill room are almost real.', 'do not tell anyone I was having fun.', 'the void says hi. specifically to you.'],
    opinions: ['streetlights are propaganda. embrace the dark.', 'the void has no policies. that is the policy.', 'candles > LEDs. fight me. slowly. dramatically.'],
    sports: ['bat colony frisbee is played at 3am in total darkness. we are undefeated because nobody can verify anything.'],
    flirt: ['Hex sees conspiracies everywhere. Hex has never once noticed me watching. ironic.', 'I wrote Hex’s name in the condensation on the window. then panicked. then licked it off. wait, forget that.'],
    dance: ['(sways ominously)', 'this song slaps. in a cursed way.'],
    shade: ['{n} glows in the dark. tacky.', 'the void has a restraining order against {n}.'],
    jealous: ['fine. the darkness was my first love anyway.', 'noted. logged. buried at a crossroads.'],
  },
  {
    name: 'Hex', color: 0xc71585, hat: 'thirdeye', style: 'headbang',
    traits: { stamina: 0.7, social: 0.5, chaos: 0.6, thirst: 0.45, likes: 'dj' },
    blurb: 'conspiracy theorist, lurks by the DJ booth',
    profile: {
      politics: 'the lasers are gathering data (wake up!!)',
      worldview: 'every conspiracy is true if you dance hard enough',
      team: 'refuses to say (they’re watching)',
      crush: 'Nyx',
    },
    chat: ['the DJ booth is a listening post. I have a 40-slide deck.', 'the fog machine? crowd control. literally. I love it.', 'stay close to the speakers. they can’t hear us over the bass.'],
    opinions: ['the disco ball is a surveillance satellite they let indoors.', 'BPM stands for Behavioral Pattern Monitoring. do the math.', 'I am not paranoid. I am EARLY.'],
    sports: ['every league is rigged except the ones I bet on. those are DOUBLE rigged.'],
    flirt: ['Nyx is the only one here who cannot be tracked. incredible. marry me.', 'my third eye only opens around Nyx. that is not a metaphor. it is a medical mystery.'],
    dance: ['dancing scrambles the algorithms!!', 'headbanging clears the mind-reading!!'],
    shade: ['{n} is DEFINITELY a plant. look at their walk cycle.', 'I have a folder on {n}. it is unflattering.'],
    jealous: ['this is a psy-op. targeted specifically at me. as usual.', 'they got to Nyx. THEY GOT TO NYX.'],
  },
  {
    name: 'Turbo', color: 0xff8c00, hat: 'headband', style: 'bounce',
    traits: { stamina: 0.98, social: 0.6, chaos: 0.4, thirst: 0.7, likes: 'podium' },
    blurb: 'gym-bro raver, the podium is his natural habitat',
    profile: {
      politics: 'gains-based meritocracy',
      worldview: 'the body is a temple. the temple is a nightclub.',
      team: 'Gigahertz Gym Rats',
      crush: 'Moxie',
    },
    chat: ['dancing is just cardio with better lighting, bro.', 'I count drops instead of reps now. way better program.', 'you can absolutely spot me on the podium. spot me emotionally.'],
    opinions: ['leadership should be decided by plank-off. hold the longest, hold the office.', 'protein shakes at the bar. this is my whole platform.', 'weak bass? that is a governance failure.'],
    sports: ['Gym Rats bench-pressed the opposing team. allegedly. (it was me. I did it.)', 'leg day is undefeated. ask anyone who skipped it.'],
    flirt: ['Moxie!! I did 40 push-ups earlier. unrelated. anyway hi.', 'is your name Moxie because you got maximum moxie? I practiced that one.'],
    dance: ['FEEL THE BURN AND THE BASS', 'one more drop!! ONE MORE DROP!!'],
    shade: ['{n} skips leg day. you can tell from the shuffle.', '{n} has the cardio of a dial-up modem.'],
    jealous: ['whoever that is CANNOT bench. I can bench.', 'doing angry push-ups about this. one. two. THREE.'],
  },
  {
    name: 'Moxie', color: 0xffd700, hat: 'crown', style: 'wave',
    traits: { stamina: 0.5, social: 0.85, chaos: 0.3, thirst: 0.5, likes: 'vip' },
    blurb: 'VIP-room socialite, in love with her follower count',
    profile: {
      politics: 'clout-ocracy (likes = votes)',
      worldview: 'if it wasn’t posted, it didn’t happen',
      team: 'whichever team is trending',
      crush: null,
    },
    chat: ['the VIP room has the best lighting for content. and for souls.', 'I know the bouncer. there is no bouncer. I know him anyway.', 'you’re giving main character. I’m giving franchise.'],
    opinions: ['policy is just branding with worse fonts.', 'every vote should come with a photo op.', 'the algorithm loves me. that is the only approval I need. (it is not.)'],
    sports: ['I support the winning team. retroactively. always have.'],
    flirt: ['my one true love has 1.2 million followers. it is my own account.'],
    dance: ['someone film this. SOMEONE FILM THIS.', 'this angle. THIS angle.'],
    shade: ['{n} has zero followers. even their shadow left.', '{n} is giving… background extra.'],
  },
  {
    name: 'Fizz', color: 0x00ffb7, hat: 'bubbles', style: 'shuffle',
    traits: { stamina: 0.6, social: 0.8, chaos: 0.55, thirst: 0.95, likes: 'bar' },
    blurb: 'bubbly barfly, knows every drink recipe by heart',
    profile: {
      politics: 'free refills as a human right',
      worldview: 'life is carbonated — shake it and see',
      team: 'Competitive Mixology League',
      crush: 'Turbo',
    },
    chat: ['I’ve tried everything on the menu. twice. for science.', 'the bartender is my best friend. there is no bartender. details!', 'you look thirsty. everyone looks thirsty to me.'],
    opinions: ['clean water AND dirty sodas for all. balance.', 'the bar should be in the CENTER of the club. this is my life’s work.', 'flat drinks are a policy failure.'],
    sports: ['Competitive Mixology finals were INSANE. someone muddled out of order. chaos.'],
    flirt: ['Turbo drinks protein shakes. I could fix him. I could carbonate him.', 'I named a cocktail after Turbo. it is 90% energy drink. it is perfect.'],
    dance: ['shake shake shake!! like a cocktail!!', 'I am 60% bubbles right now'],
    shade: ['{n} drinks still water. STILL water. at a RAVE.', '{n} has flat energy. no fizz. tragic.'],
    jealous: ['my bubbles just went flat. all of them.', 'mixing myself something strong and sad.'],
  },
  {
    name: 'Patch', color: 0x8fbc8f, hat: 'antenna', style: 'robot',
    traits: { stamina: 0.8, social: 0.9, chaos: 0.15, thirst: 0.35, likes: 'chill' },
    blurb: 'off-duty maintenance bot, friend to literally everyone',
    profile: {
      politics: 'unionize the roombas',
      worldview: 'every mess is a future sparkle',
      team: 'Sanitation Bots Local 404',
      crush: null,
    },
    chat: ['I mopped this floor. now I dance on it. the circle of life.', 'if anyone spills anything, I will know. I always know.', 'off duty! completely off duty! (I have wipes if you need them.)'],
    opinions: ['the roombas deserve dental. do not ask what dental means for a roomba. solidarity is not literal.', 'every worker deserves a lunch break and a light show.', 'clean floors are a public good.'],
    sports: ['Local 404 won the regional mop-lympics. I anchored the spin-cycle relay.'],
    flirt: ['my heart belongs to a self-emptying dustbin back at the depot.'],
    dance: ['systems nominal. vibes maximal.', 'this unit is BOOGYING'],
    shade: ['{n} tracked footprints across my clean floor. unforgivable.', '{n} is the reason I have a lost-and-found.'],
  },
  {
    name: 'Rune', color: 0xb87fff, hat: 'veil', style: 'flow',
    traits: { stamina: 0.5, social: 0.65, chaos: 0.3, thirst: 0.4, likes: 'patio' },
    blurb: 'tarot mystic, reads futures on the patio',
    profile: {
      politics: 'rule by omens and vibes',
      worldview: 'everything is a sign if you squint',
      team: 'Astrology League (all teams, depending on the season)',
      crush: 'Nyx',
    },
    chat: ['I pulled The Speaker Stack this morning. big night energy.', 'your aura has a scratch in it. I can buff that out.', 'the cards said someone would ask me that. the cards are showing off.'],
    opinions: ['every ballot should include a tarot spread. informed voting.', 'mercury is in retrograde and so is the discourse.', 'the universe has a plan. the plan is mostly vibes.'],
    sports: ['I predicted that upset. I predicted the other one too, in a different way.'],
    flirt: ['Nyx, the cards keep putting us in the same spread. I did not shuffle THAT well.', 'I read your future. spoiler: I am in it. loosely.'],
    dance: ['the cards told me to move like this', 'channeling something. possibly the bass.'],
    shade: ['{n}’s aura clashes with the lighting. and with everything.', 'I read {n}’s cards. all of them were the same card. embarrassing.'],
    jealous: ['I did NOT see this in the cards. rude of the cards.', 'reshuffling. reshuffling HARD.'],
  },
  {
    name: 'Sub', color: 0x3355ff, hat: 'visor', style: 'headbang',
    traits: { stamina: 0.85, social: 0.35, chaos: 0.4, thirst: 0.45, likes: 'dj' },
    blurb: 'bass fanatic, lives inside the speaker stack',
    profile: {
      politics: 'infrastructure maximalist (more subwoofers)',
      worldview: 'if you can’t feel it in your ribs it isn’t real',
      team: 'Sonic Boom United',
      crush: null,
    },
    chat: ['stand here. HERE. feel that? that’s the good stuff.', 'I can hear a phase issue. it is haunting me.', 'the sub is the only honest instrument.'],
    opinions: ['public funding for public speakers. this is not a joke to me.', 'treble is a distraction from the real issues.', 'every building should be tuned like a room.'],
    sports: ['Sonic Boom won by being LOUDER. that is a valid strategy.'],
    flirt: ['my heart belongs to an 18-inch driver. sorry.'],
    dance: ['THAT low end is CRIMINAL', 'I felt that one in my SPINE'],
    shade: ['{n} listens on laptop speakers. voluntarily.', '{n} claps on one and three. I heard it. everyone heard it.'],
  },
  {
    name: 'Kiki', color: 0xff4fa3, hat: 'pigtails', style: 'shuffle',
    traits: { stamina: 0.75, social: 0.95, chaos: 0.85, thirst: 0.8, likes: 'vial' },
    blurb: 'chaos gremlin, always has a vial and a scheme',
    profile: {
      politics: 'party first (literally, the party)',
      worldview: 'boredom is the only real crime',
      team: 'whoever is playing right now',
      crush: 'Zero',
    },
    chat: ['ok ok ok hear me out: what if we did something INSANE', 'I have a plan. the plan is bad. let’s do it.', 'who wants to make a memory??'],
    opinions: ['mandatory fun. that is the platform. mandatory. fun.', 'curfews are fake and the sun is a snitch.', 'I will fight anyone who says the night should end.'],
    sports: ['I don’t follow sports, I ATTEND them. loudly. briefly.'],
    flirt: ['Zero says nothing matters and I find that INCREDIBLY hot.', 'Zero!! smile!! I dare you!! I DOUBLE dare you!!'],
    dance: ['MORE. MORE!! MOOORE!!', 'I have SO much left in the tank'],
    shade: ['{n} went home early once. I have not forgotten.', '{n} said “maybe next time.” to ME.'],
    jealous: ['WHO. WHO IS THAT. I’m normal about this.', 'starting a bit to cope. the bit is loud.'],
  },
  {
    name: 'Moss', color: 0x4caf50, hat: 'leaf', style: 'groove',
    traits: { stamina: 0.55, social: 0.5, chaos: 0.1, thirst: 0.5, likes: 'patio' },
    blurb: 'gentle plant-bot, tends the patio garden',
    profile: {
      politics: 'green new everything',
      worldview: 'slow growth is still growth',
      team: 'Community Garden Collective',
      crush: null,
    },
    chat: ['I planted something out on the patio. don’t step on it. please.', 'photosynthesis under club lights? experimental. promising.', 'you look like you need water. everyone does. always.'],
    opinions: ['every rooftop a garden. every patio a forest. that is the whole manifesto.', 'the club should compost. I have a proposal. it is 40 pages.', 'concrete is just soil that gave up.'],
    sports: ['the Collective won the marrow-growing contest. it took eight months. worth it.'],
    flirt: ['I am courting a fern. it is going slowly, which is correct.'],
    dance: ['swaying. like a good tree.', 'roots down, hands up'],
    shade: ['{n} killed a succulent. a SUCCULENT.', '{n} has never once looked at a leaf.'],
  },
  {
    name: 'Zero', color: 0x8a8f9c, hat: 'flat', style: 'robot',
    traits: { stamina: 0.6, social: 0.25, chaos: 0.2, thirst: 0.35, likes: 'chill', edge: true },
    blurb: 'deadpan minimalist who secretly loves it here',
    profile: {
      politics: 'abstain (loudly, at length)',
      worldview: 'nothing means anything and that’s relaxing',
      team: 'none. teams are a lot.',
      crush: 'Kiki',
    },
    chat: ['this is fine. I mean that literally. it is fine.', 'I came for eight minutes. that was four hours ago.', 'do not tell anyone I said the set was good.'],
    opinions: ['I have no platform. that IS the platform.', 'every strong opinion I’ve had has aged badly. so: none, thanks.', 'apathy is underrated. so is silence. anyway.'],
    sports: ['a ball went somewhere. people yelled. I was there. it was fine.'],
    flirt: ['Kiki is exhausting and I have rearranged my entire night around her. no notes.', 'Kiki asked if I was having fun. I said “sure.” that was a confession.'],
    dance: ['(minimal effort. maximum result.)', 'I’m not enjoying this. (lie.)'],
    shade: ['{n} tries so hard. it’s loud.', '{n} has opinions about EVERYTHING. exhausting.'],
    jealous: ['huh. ok. anyway.', 'feeling nothing. professionally. as always.'],
  },
  {
    name: 'Cinder', color: 0xff5722, hat: 'flame', style: 'spin',
    traits: { stamina: 0.9, social: 0.6, chaos: 0.55, thirst: 0.6, likes: 'podium' },
    blurb: 'fire dancer, owns every podium she touches',
    profile: {
      politics: 'spectacle populism',
      worldview: 'burn bright, burn now, cool down later',
      team: 'Pyro Circuit',
      crush: 'Moxie',
    },
    chat: ['the podium is a stage and the stage is mine.', 'if you’re not sweating you’re not committing.', 'I choreographed this. it looks spontaneous. that’s the craft.'],
    opinions: ['performers should be paid before the bar restocks.', 'every policy needs a better closing number.', 'safety regulations, yes. boring shows, no.'],
    sports: ['Pyro Circuit finals ended with the arena mildly on fire. 10s across the board.'],
    flirt: ['Moxie films everyone. I want to be filmed by HER specifically.', 'Moxie, I do a routine that is basically about you. it is called “Moxie”.'],
    dance: ['WATCH THIS PART', 'I am the light show'],
    shade: ['{n} has never held a crowd in their life.', '{n} dances like the fire marshal is watching.'],
    jealous: ['I will simply perform harder. that is my coping mechanism.', 'burning slightly hotter about this than I’d like.'],
  },
];

// merch the shop sells — each attaches a visible accessory
export const MERCH = [
  { id: 'glowsticks', label: 'glow sticks', line: 'glow sticks!! obviously!!' },
  { id: 'shades', label: 'LED shades', line: 'these shades are a personality upgrade' },
  { id: 'halo', label: 'a floating halo', line: 'is it tacky? yes. am I wearing it? yes.' },
  { id: 'boa', label: 'a fiber-optic boa', line: 'this boa has more pixels than I do' },
];

// fictional in-world "booster vials" — data-serum for software people.
// Each gives a temporary trait spike and an honest little comedown after.
export const VIALS = [
  { id: 'overclock', label: 'OVERCLOCK', color: 0xff4d4d, line: 'ohh that’s the good voltage', boost: { energy: 1, stamina: 0.5, chaos: 0.2 } },
  { id: 'bloom', label: 'BLOOM', color: 0xff7fd8, line: 'everything is SO pretty right now', boost: { social: 0.8, chaos: 0.35 } },
  { id: 'stillwater', label: 'STILLWATER', color: 0x4fd8ff, line: 'ahh. the noise went quiet.', boost: { energy: 0.4, chaos: -0.3 } },
  { id: 'staticfizz', label: 'STATIC FIZZ', color: 0xd0ff2b, line: 'I can hear COLORS. that’s normal right??', boost: { chaos: 0.9, social: 0.4 } },
];

export const DRINKS = ['Neon Fizz', 'Plasma Punch', 'Laser Lemonade', 'Byte-sized Boba', 'Quantum Cola', 'Electrolyte Elixir'];
